add user model, but new method can't use yet
Helomair/my-5xRuby-training pull request #10
Opened 2019-04-10 14:27 UTC by Helomair

2019-04-10 16:50 UTC, elct9620 approved these changes

2019-04-18 13:32 UTC, elct9620 requested changes

2019-04-18 13:32 UTC, elct9620 commented on config/environments/test.rb
> +[MyRailsApp]::Application.configure do |config|
沒必要用這個做 Session 功能

2019-04-18 13:32 UTC, elct9620 commented on app/controllers/sessions_controller.rb
> +  def login
一般情況下應該要盡量維持基本的 CRUD (Ex. new + create) 的組合，而不是去產生新的方法增加複雜度

2019-04-18 20:57 UTC, Helomair commented on app/controllers/sessions_controller.rb
> +  def login
所以login跟verify改回來嗎，這樣會影響很多嗎

2019-04-20 14:07 UTC, merged