part14, add end_time, done
Helomair/my-5xRuby-training pull request #9
Opened 2019-04-02 11:40 UTC by Helomair

2019-04-04 03:44 UTC, elct9620 requested changes

2019-04-04 03:44 UTC, elct9620 commented on app/controllers/tasks_controller.rb
> +        if (params[:status] == nil) && (params[:search] == nil)
Ruby 在這類型得處理應該用 `params[:status].nil?` 的方式

2019-04-04 03:44 UTC, elct9620 commented on app/views/tasks/index.html.erb
> +<div style="margin: 10px 5px 5px 5px">
應該用 bootstrap or css 控制外觀

2019-04-07 10:30 UTC, elct9620 requested changes

2019-04-07 10:30 UTC, elct9620 commented on app/controllers/tasks_controller.rb
> +        if (params[:status].nil? ) && (params[:search].nil? )
改 `nil?` 括號就不用寫了

2019-04-07 10:30 UTC, elct9620 commented on app/views/tasks/index.html.erb
> +    <%= link_to ('<button>'+t("task.status.all")+'</button>').html_safe, tasks_path(status:nil), id: "all"%>
正常狀況不應該用 `html_safe` 這有其他寫法

```erb
<%= link_to task_path(status: nil), id: "all" do %>
  <button><%= t("task.status.all") %></button>
<% end %>
```

2019-04-07 10:30 UTC, elct9620 commented on spec/rails_helper.rb
> +Rails.env = "test"
正常情況不用加這個 Rails 就要會切到測試環境。

2019-04-07 10:30 UTC, elct9620 commented on spec/rails_helper.rb
> +  ActiveRecord::Base.establish_connection
一樣，正確設定的 Rspec 不應該需要手動設定

2019-04-07 13:48 UTC, Helomair commented on spec/rails_helper.rb
> +Rails.env = "test"
我加了就過了，不然都會用到developmenet的資料庫

2019-04-07 13:48 UTC, Helomair commented on spec/rails_helper.rb
> +  ActiveRecord::Base.establish_connection
這個應該是沒影響的，我會刪掉

2019-04-07 14:33 UTC, elct9620 commented on spec/rails_helper.rb
> +Rails.env = "test"
正常不會，你是怎麼下 rspec 指令的？

2019-04-07 14:41 UTC, elct9620 commented on .travis.yml
> +script: bundle exec rake spec
正常的環境直接做 `bundle exec rspec` 要會動才對

2019-04-08 08:25 UTC, Helomair commented on spec/rails_helper.rb
> +Rails.env = "test"
bundle exec rspec

2019-04-08 09:06 UTC, Helomair commented
把bundle install拉進script就過了

2019-04-08 12:53 UTC, elct9620 requested changes

2019-04-08 12:53 UTC, elct9620 commented on Gemfile
> +  gem 'database_rewinder'
這應該只要用其中一種就可以了

2019-04-08 12:53 UTC, elct9620 commented on spec/spec_helper.rb
> +ENV['RAILS_ENV'] ||= 'test'
這邊還是有，這是多餘的不應該出現在這才對

2019-04-08 15:04 UTC, elct9620 commented
是說你的 Travis CI 設定有給 `RAILS_ENV` 嗎？

2019-04-08 19:06 UTC, Helomair commented
沒有，這要怎麼設定

2019-04-09 15:29 UTC, merged